2024-12-09 16:39:36,183 INFO    MainThread:97319 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-12-09 16:39:36,183 INFO    MainThread:97319 [wandb_setup.py:_flush():79] Configure stats pid to 97319
2024-12-09 16:39:36,183 INFO    MainThread:97319 [wandb_setup.py:_flush():79] Loading settings from /Users/shengkangchen/.config/wandb/settings
2024-12-09 16:39:36,183 INFO    MainThread:97319 [wandb_setup.py:_flush():79] Loading settings from /Users/shengkangchen/Documents/MobileMultiRobot_RL/wandb/settings
2024-12-09 16:39:36,183 INFO    MainThread:97319 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-12-09 16:39:36,183 INFO    MainThread:97319 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-12-09 16:39:36,183 INFO    MainThread:97319 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'MADDPG/main.py', 'program_abspath': '/Users/shengkangchen/Documents/MobileMultiRobot_RL/MADDPG/main.py', 'program': '/Users/shengkangchen/Documents/MobileMultiRobot_RL/MADDPG/main.py'}
2024-12-09 16:39:36,183 INFO    MainThread:97319 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-09 16:39:36,184 INFO    MainThread:97319 [wandb_init.py:_log_setup():533] Logging user logs to /Users/shengkangchen/Documents/MobileMultiRobot_RL/wandb/run-20241209_163936-aphtqv8g/logs/debug.log
2024-12-09 16:39:36,184 INFO    MainThread:97319 [wandb_init.py:_log_setup():534] Logging internal logs to /Users/shengkangchen/Documents/MobileMultiRobot_RL/wandb/run-20241209_163936-aphtqv8g/logs/debug-internal.log
2024-12-09 16:39:36,184 INFO    MainThread:97319 [wandb_init.py:init():619] calling init triggers
2024-12-09 16:39:36,184 INFO    MainThread:97319 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {}
2024-12-09 16:39:36,184 INFO    MainThread:97319 [wandb_init.py:init():669] starting backend
2024-12-09 16:39:36,184 INFO    MainThread:97319 [wandb_init.py:init():673] sending inform_init request
2024-12-09 16:39:36,186 INFO    MainThread:97319 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-12-09 16:39:36,187 INFO    MainThread:97319 [wandb_init.py:init():686] backend started and connected
2024-12-09 16:39:36,190 INFO    MainThread:97319 [wandb_init.py:init():781] updated telemetry
2024-12-09 16:39:36,216 INFO    MainThread:97319 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-12-09 16:39:44,588 WARNING MainThread:97319 [wandb_init.py:init():1260] interrupted
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pettingzoo_m4/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/opt/anaconda3/envs/pettingzoo_m4/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 817, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pettingzoo_m4/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pettingzoo_m4/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pettingzoo_m4/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pettingzoo_m4/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pettingzoo_m4/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-12-09 16:39:44,593 WARNING MsgRouterThr:97319 [router.py:message_loop():75] message_loop has been closed
